apiVersion: v1
data:
  loki-stack-datasource.yaml: "apiVersion: 1\ndatasources:\n- name: Loki\n  type:
    loki\n  access: proxy\n  url: \"http://loki:3100\"\n  version: 1\n  isDefault:
    false \n  jsonData:\n    {}"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-03-31T13:11:45Z"
  labels:
    app: loki-stack
    app.kubernetes.io/managed-by: Helm
    chart: loki-stack-2.10.3
    grafana_datasource: "1"
    heritage: Helm
    release: loki
  name: loki-loki-stack
  namespace: monitoring
  resourceVersion: "93783"
  uid: 11edbd2d-af5f-468a-a49a-58847b0b8096
