{
 "title": "Pods Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 5 Memory Consuming Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"demo-app\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"demo-app\"}[1h])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"demo-app\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"demo-app\", cpu=\"total\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}